sudo: false
language: ruby
rvm:
- 2.0
- 2.1
- 2.2
- 2.3
- ruby-head
- jruby-19mode
env:
- COVERALL=1

notifications:
  recipients:
  - weppos@weppos.net

matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-19mode
