language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - jruby-9.1.5.0
  - ruby-head

cache:
  - bundler

env:
  - COVERALL=1

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-9.1.5.0

before_install:
  - rvm get latest
  - gem install bundler
